make_main_screen
mvrlrd/PlaylistMaker-YP pull request #1
Opened 2022-11-12 14:19 UTC by mvrlrd

2022-11-28 21:22 UTC, MagicUnderHood requested changes

2022-11-28 21:22 UTC, MagicUnderHood commented on app/src/main/res/values-night/styles.xml
> +    <style name="MainMenuButtonStyle" parent="Widget.MaterialComponents.Button">
Обрати внимание на требование:  
`Для «Главного экрана» стиль кнопки наследуется от Widget.MaterialComponents.Button.UnelevatedButton`

2022-11-28 21:22 UTC, MagicUnderHood commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/ys_display_regular</item>
Используемый шрифт не добавлен в проект (или не закоммичен в гит)

2022-11-28 21:22 UTC, MagicUnderHood commented on app/src/main/res/layout/activity_settings.xml
> +            style="@style/IconStyle"
Обрати внимание на требование:  При нажатии на кнопку «Поделиться приложением» появляется диалог для шаринга сообщения в любой из доступных мессенджеров на устройстве. Текст сообщения содержит ссылку на курс по Андроид-разработке в Практикуме.

2022-11-30 07:48 UTC, MagicUnderHood commented
Замечания исправлены

2023-01-24 21:31 UTC, gusar-off reviewed
Еще хочу обратить внимание, что в рамках этого пр видны изменения из прошлых спринтов. Когда отдаешь задание на проверку нужно, чтобы пр содержал только код, реализующий спринт. Для этого нужно каждое принятое задание сливать в мастер и для нового задания делать новую ветку от мастера, тогда получится отображать только актуальные изменения

2023-01-24 21:31 UTC, gusar-off commented on app/src/main/java/ru/mvrlrd/playlistmaker/model/TrackDb.kt
> +class TrackDb {
Данный класс лучше сделать утилитным, объявив объектом (ключевое слово `object`). Тогда не придется создавать новые инстансы, а можно будет переиспользовать как синглтон

2023-01-24 21:31 UTC, gusar-off commented on app/src/main/java/ru/mvrlrd/playlistmaker/MyApplication.kt
> +        val  trackDb : TrackDb = TrackDb()
И тогда можно будет не хранить элементы адаптера на уровне `Application`, все равно в ближайшем спринте моки заменятся на реальные вызовы АПИ, поэтому предлагаю убрать это

2023-01-24 21:31 UTC, gusar-off commented on app/src/main/java/ru/mvrlrd/playlistmaker/MediatekaActivity.kt
> +class MediatekaActivity : AppCompatActivity() {
Пока что нет необходимости реализовывать логику данного экрана, все равно в будущем переделывать

2023-02-12 20:22 UTC, merged